### PR TITLE
enable to specify default branch

### PR DESCRIPTION
**Pull request by h-babazono**
Sometimes master is not base branch, but gocat only use master as default.
So I add new envvar and use it as base branch.

### CODE REVIEW

**Comment by naoki85** [comment]
Is this PR related to https://github.com/zaiminc/gocat/pull/180 ?

**Comment by h-babazono** [comment]
> Is this PR related to #180 ?

Yes, that PR enabled to deploy project from any branch if there's specification on project.yaml.
This PR enabled to operate `CONFIG_MANIFEST_REPOSITORY` if its base is not master.

**Review by boy2 — APPROVED** [review]
よさそう！

**Review by naoki85 — APPROVED** [review]
👍

**Review by autumo — APPROVED** [review]
Let's keep working on this fix until we can get the default remote branch in go-git

**Pull request merged**
